In [1]:
import numpy as np

In [4]:
a = np.array([[1,4],[9,16],[25,36]])
print(a)

[[ 1  4]
 [ 9 16]
 [25 36]]


In [6]:
print(np.sqrt(a))

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [7]:
print(np.exp(a))

[[2.71828183e+00 5.45981500e+01]
 [8.10308393e+03 8.88611052e+06]
 [7.20048993e+10 4.31123155e+15]]


In [11]:
b = np.array([[1,4],[None,16],[25,36]])
print(b)

[[1 4]
 [None 16]
 [25 36]]


In [14]:
import pandas as pd

In [19]:
data= pd.read_csv('Lemonade.csv')
data = np.array(data)

In [22]:
print(data[2,-1])

15


In [28]:
b=np.array([1,2,3,4,5,6,7,8,9])
print(b)

[1 2 3 4 5 6 7 8 9]


In [50]:
c=b[9:3:-1]
print(c)

[9 8 7 6 5]
