In [19]:
import numpy as np

In [20]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [21]:
a.dtype

dtype('int32')

In [22]:
b= np.array([1.1,2.2,3.3])
print(b)

[1.1 2.2 3.3]


In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.diag(a)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
a=[1,2,3,4,5,6,4,7]


In [39]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 4, 4, 4, 7,
       7, 7])